In [1]:
import os, os.path as op, pandas as pd, numpy as np, re
from glob import glob
from functools import partial
from IPython.display import display
from durons import *

In [2]:
file = "/Volumes/GoogleDrive/Mój dysk/packages/durons/logs/DEPHC_01-emreg_MIND_1_K.log" #example log file

### Show a list of all the stimuli/events that occurred in the log file:

In [3]:
stimuli_from_log(file, participant=None, sep = '\t', skiprows = 3, sort = True)

['10',
 '111',
 '20',
 '3',
 '4',
 '5',
 '6',
 '7',
 'Instrukcja',
 'NEU1',
 'NEU2',
 'NEU3',
 'NEU4',
 'NEU5',
 'NEU6',
 'NEU7',
 'NEU8',
 'SAD1',
 'SAD10',
 'SAD11',
 'SAD12',
 'SAD2',
 'SAD3',
 'SAD4',
 'SAD5',
 'SAD6',
 'SAD7',
 'SAD8',
 'SAD9',
 'fix',
 'mindful',
 'ogladaj',
 'pytanie',
 'short_fix']

### Export all the stimuli from pre-defined blocks

In [4]:
blocks =  'mindful|ogladaj' #each block starts with either a 'mindful' or a 'ogladaj'[watch] stimulus
until = 'pytanie' #each block ends when a 'pytanie'[question] stimulus happens
codes = 'NEU|SAD' # we will be looking for durations and onsets for any stimulus that has "NEU" or "SAD" in its name

In [5]:
get_blocks(file, codes, blocks, until, participant=None, sep = '\t', skiprows = 3, sort = True)

{'NEU1': 'ogladaj_NEU',
 'NEU2': 'ogladaj_NEU',
 'NEU3': 'ogladaj_NEU',
 'NEU4': 'ogladaj_NEU',
 'NEU5': 'ogladaj_NEU',
 'NEU6': 'ogladaj_NEU',
 'NEU7': 'ogladaj_NEU',
 'NEU8': 'ogladaj_NEU',
 'SAD1': 'mindful_SAD',
 'SAD10': 'ogladaj_SAD',
 'SAD11': 'mindful_SAD',
 'SAD12': 'mindful_SAD',
 'SAD2': 'mindful_SAD',
 'SAD3': 'mindful_SAD',
 'SAD4': 'mindful_SAD',
 'SAD5': 'mindful_SAD',
 'SAD6': 'mindful_SAD',
 'SAD7': 'ogladaj_SAD',
 'SAD8': 'ogladaj_SAD',
 'SAD9': 'ogladaj_SAD'}

### Calculate durations and onsets without any pre-defined stimulus categorization
##### Doesn't make much sense, but why the hell not?

In [6]:
dur1 = durons(file, stimuli=None, participant=None, sep = '\t', skiprows = 3, sort = True, s = True)

In [7]:
for stim in dur1.keys():
    print(stim)
    display(dur1[stim])

NEU1


onsets  durations
0  3.0625    10.0167

NEU2


onsets  durations
0  13.0959    10.0167

NEU3


onsets  durations
0  219.0804    10.0167

NEU4


onsets  durations
0  229.1138    10.0167

NEU5


onsets  durations
0  348.6811    10.0167

NEU6


onsets  durations
0  358.7145    10.0167

NEU7


onsets  durations
0  132.6632    10.0167

NEU8


onsets  durations
0  142.6966    10.0167

SAD1


onsets  durations
0  46.2627    10.0167

SAD10


onsets  durations
0  315.5142    10.0167

SAD11


onsets  durations
0  262.2806    10.0167

SAD12


onsets  durations
0  272.314    10.0167

SAD2


onsets  durations
0  56.2961    10.0167

SAD3


onsets  durations
0  175.8635    10.0167

SAD4


onsets  durations
0  185.8969    10.0167

SAD5


onsets  durations
0  391.8813    10.0167

SAD6


onsets  durations
0  401.9147    10.0167

SAD7


onsets  durations
0  89.463    10.0167

SAD8


onsets  durations
0  99.4964    10.0167

SAD9


onsets  durations
0  305.4809    10.0167

fix


onsets  durations
0   40.1960     3.0167
1   83.3963     3.0167
2  126.5965     3.0167
3  169.7968     3.0167
4  212.9970     3.0167
5  256.2139     3.0167
6  299.4142     3.0167
7  342.6144     3.0167
8  385.8146     3.0167

mindful


onsets  durations
0   43.2294     3.0167
1  172.8301     3.0167
2  259.2473     3.0167
3  388.8480     3.0167

ogladaj


onsets  durations
0    0.0292     3.0167
1   86.4296     3.0167
2  129.6299     3.0167
3  216.0470     3.0167
4  302.4475     3.0167
5  345.6477     3.0167

short_fix


onsets  durations
0   31.1460     1.0167
1   74.3462     1.0166
2  117.5465     1.0167
3  160.7467     1.0167
4  203.9470     1.0167
5  247.1639     1.0167
6  290.3641     1.0167
7  333.5643     1.0166
8  376.7646     1.0167
9  419.9648     1.0167

### It is, however, always better to use pre-defined blocks:

In [8]:
b = get_blocks(file, codes, blocks, until, participant=None, sep = '\t', skiprows = 3, sort = True)

In [9]:
b

{'NEU1': 'ogladaj_NEU',
 'NEU2': 'ogladaj_NEU',
 'NEU3': 'ogladaj_NEU',
 'NEU4': 'ogladaj_NEU',
 'NEU5': 'ogladaj_NEU',
 'NEU6': 'ogladaj_NEU',
 'NEU7': 'ogladaj_NEU',
 'NEU8': 'ogladaj_NEU',
 'SAD1': 'mindful_SAD',
 'SAD10': 'ogladaj_SAD',
 'SAD11': 'mindful_SAD',
 'SAD12': 'mindful_SAD',
 'SAD2': 'mindful_SAD',
 'SAD3': 'mindful_SAD',
 'SAD4': 'mindful_SAD',
 'SAD5': 'mindful_SAD',
 'SAD6': 'mindful_SAD',
 'SAD7': 'ogladaj_SAD',
 'SAD8': 'ogladaj_SAD',
 'SAD9': 'ogladaj_SAD'}

In [10]:
dur2 = durons(file, stimuli=b, participant=None, sep = '\t', skiprows = 3, sort = True, s = True)

In [11]:
for stim in dur2.keys():
    print(stim)
    display(dur2[stim])

mindful_SAD


onsets  durations
0   46.2627    10.0167
1   56.2961    10.0167
2  175.8635    10.0167
3  185.8969    10.0167
4  262.2806    10.0167
5  272.3140    10.0167
6  391.8813    10.0167
7  401.9147    10.0167

ogladaj_NEU


onsets  durations
0    3.0625    10.0167
1   13.0959    10.0167
2  132.6632    10.0167
3  142.6966    10.0167
4  219.0804    10.0167
5  229.1138    10.0167
6  348.6811    10.0167
7  358.7145    10.0167

ogladaj_SAD


onsets  durations
0   89.4630    10.0167
1   99.4964    10.0167
2  305.4809    10.0167
3  315.5142    10.0167

#### The durations and onsets are Pandas DataFrames stored inside Python dictionaries:
##### It is, therefore, fairly easy to address them.

In [12]:
type(dur2)

dict

In [13]:
type(dur2['ogladaj_NEU'])

pandas.core.frame.DataFrame

In [14]:
dur2['ogladaj_NEU']

onsets  durations
0    3.0625    10.0167
1   13.0959    10.0167
2  132.6632    10.0167
3  142.6966    10.0167
4  219.0804    10.0167
5  229.1138    10.0167
6  348.6811    10.0167
7  358.7145    10.0167

In [15]:
mat_filename = file.split('.')[0] + '.mat'

### Export the duration and onset values into MATLAB and SPM-ready .mat file
##### Alphabetically ordered:

In [16]:
durons_savemat(durons_dict=dur2, filename=mat_filename, sort = True, output=True)

{'names': array(['mindful_SAD', 'ogladaj_NEU', 'ogladaj_SAD'], dtype=object),
 'durations': array([array([10.0167, 10.0167, 10.0167, 10.0167, 10.0167, 10.0167, 10.0167,
        10.0167]),
        array([10.0167, 10.0167, 10.0167, 10.0167, 10.0167, 10.0167, 10.0167,
        10.0167]),
        array([10.0167, 10.0167, 10.0167, 10.0167])], dtype=object),
 'onsets': array([array([ 46.2627,  56.2961, 175.8635, 185.8969, 262.2806, 272.314 ,
        391.8813, 401.9147]),
        array([  3.0625,  13.0959, 132.6632, 142.6966, 219.0804, 229.1138,
        348.6811, 358.7145]),
        array([ 89.463 ,  99.4964, 305.4809, 315.5142])], dtype=object)}

##### Original order maintained:

In [17]:
durons_savemat(durons_dict=dur2, filename=mat_filename, sort = False, output=True)

{'names': array(['mindful_SAD', 'ogladaj_NEU', 'ogladaj_SAD'], dtype=object),
 'durations': array([array([10.0167, 10.0167, 10.0167, 10.0167, 10.0167, 10.0167, 10.0167,
        10.0167]),
        array([10.0167, 10.0167, 10.0167, 10.0167, 10.0167, 10.0167, 10.0167,
        10.0167]),
        array([10.0167, 10.0167, 10.0167, 10.0167])], dtype=object),
 'onsets': array([array([ 46.2627,  56.2961, 175.8635, 185.8969, 262.2806, 272.314 ,
        391.8813, 401.9147]),
        array([  3.0625,  13.0959, 132.6632, 142.6966, 219.0804, 229.1138,
        348.6811, 358.7145]),
        array([ 89.463 ,  99.4964, 305.4809, 315.5142])], dtype=object)}

##### Custom order can easily be forced with a list:

In [18]:
durons_savemat(durons_dict=dur2, filename=mat_filename, sort = ['ogladaj_NEU', 'ogladaj_SAD', 'mindful_SAD'], output=True)

{'names': array(['ogladaj_NEU', 'ogladaj_SAD', 'mindful_SAD'], dtype=object),
 'durations': array([array([10.0167, 10.0167, 10.0167, 10.0167, 10.0167, 10.0167, 10.0167,
        10.0167]),
        array([10.0167, 10.0167, 10.0167, 10.0167]),
        array([10.0167, 10.0167, 10.0167, 10.0167, 10.0167, 10.0167, 10.0167,
        10.0167])], dtype=object),
 'onsets': array([array([  3.0625,  13.0959, 132.6632, 142.6966, 219.0804, 229.1138,
        348.6811, 358.7145]),
        array([ 89.463 ,  99.4964, 305.4809, 315.5142]),
        array([ 46.2627,  56.2961, 175.8635, 185.8969, 262.2806, 272.314 ,
        391.8813, 401.9147])], dtype=object)}